# Generated by Django 3.0.4 on 2020-03-19 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='owner', to='purrfectpets_project.UserProfile')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('animalType', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photos', models.ImageField(upload_to='')),
                ('awwCount', models.IntegerField()),
                ('awwSenders', models.ManyToManyField(related_name='awwSenders', to='purrfectpets_project.UserProfile')),
            ],
        ),
    ]
