# Generated by Django 3.0.4 on 2020-03-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectpets_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photos',
        ),
    ]
