# Generated by Django 3.0.4 on 2020-03-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectpets_project', '0002_remove_pet_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentMaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='purrfectpets_project.UserProfile')),
                ('commentAbout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='purrfectpets_project.Pet')),
                ('timeDate', models.DateTimeField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
