# Generated by Django 2.2.3 on 2020-03-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectpets_project', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animalType',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pet',
            name='bio',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
