# Generated by Django 2.2.3 on 2020-03-20 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectpets_project', '0004_auto_20200320_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('typ', models.CharField(choices=[('DO', 'Dog'), ('CA', 'Cat'), ('FI', 'Fish'), ('RE', 'Reptile'), ('RO', 'Rodent'), ('OT', 'Other')], max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='animalType',
            field=models.ForeignKey(default='OT', on_delete=django.db.models.deletion.SET_DEFAULT, to='purrfectpets_project.AnimalType'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='awwCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='purrfectpets_project.UserProfile'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='purrfectpets_project.Pet')),
            ],
        ),
    ]
